# Generated by Django 5.0.1 on 2024-04-29 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_cart_created_by_alter_order_placed_by_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CardItem',
            new_name='CartItem',
        ),
    ]
