# Generated by Django 5.0.1 on 2024-04-29 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_rename_carditem_cartitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
